### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-BelenCatalan#1]
Buen trabajo @BelenCatalan !

### Algunas pistas para acabarlo:

- [x] En el componente del listado hay que recorrer el array de pokemons que le llega por props y pintar una tarjeta por cada uno.
- [x] Usa el estado de App.js para guardar los datos.
- [x] En App.js usa los datos guardados en el estado para pasárselos al componente PokeList.
- [x] Importa los datos en App.js y no en PokeList.js
- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Pinta los tipos con un `ul` y varios `li`.

### Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by BelenCatalan** [comment]
Hoola Miguel,

creo que hay alguna cosa que no está ok, es posible?
- Importa los datos en App.js y no en PokeList.js. Los he importado en App, pero los he trabajado ahí también y luego pasado por props.
- Pinta los tipos con un ul y varios li : este no lo tengo claro, es porque yo he puesto además un div que recubre el ul y los li? No debería estar ahí.
- Pokemon tiene solo la tarjeta, pero claro al trabajar los datos en App y no en PokeList, el listado es como si lo hiciese App no?

Gracias!

**Comment by migueldelmazo** [comment]
Hooola @BelenCatalan ,

Te contesto señoría:

**Importa los datos en App.js y no en PokeList.js. Los he importado en App, pero los he trabajado ahí también y luego pasado por props:** Tienes razón, lo he quitado del issue.

**Pinta los tipos con un ul y varios li : este no lo tengo claro, es porque yo he puesto además un div que recubre el ul y los li? No debería estar ahí.:** En esta línea hay que hacer un map para pintar un ul con N li dentro, ya que los tipos también son un array. https://github.com/Adalab/modulo-3-evaluacion-intermedia-BelenCatalan/blob/master/src/components/Pokemon.js#L12

**Pokemon tiene solo la tarjeta, pero claro al trabajar los datos en App y no en PokeList, el listado es como si lo hiciese App no?** Creo que te entiendo. Este map debemos hacerlo dentro de PokeList no dentro de App.

Gracias!
